"""
Graph Visualization Module.

This module provides functions to visualize the state-space graph
generated by the simulation engine using graphviz.
"""
import networkx as nx
from networkx.drawing.nx_agraph import to_agraph

def generate_graph_visualization(graph: nx.DiGraph, output_path: str):
    """
    Generates a visualization of the state graph and saves it to a file.

    Args:
        graph: The networkx graph to visualize.
        output_path: The path to save the image file (e.g., 'graph.png').
    """
    if not graph or graph.number_of_nodes() == 0:
        print("Graph is empty. Nothing to visualize.")
        return

    # Create a pygraphviz graph from the networkx graph
    agraph = to_agraph(graph)

    # Customize the graph's appearance
    agraph.node_attr['shape'] = 'box'
    agraph.node_attr['fontsize'] = '10'
    agraph.edge_attr['fontsize'] = '8'

    # Set node labels to be a simplified representation of the state
    for node in graph.nodes():
        state_dict = dict(node)
        label = "\n".join([f"{k}={v}" for k, v in state_dict.items()])
        agraph.get_node(node).attr['label'] = label

    # Set edge labels to be the event name
    for u, v, data in graph.edges(data=True):
        agraph.get_edge(u, v).attr['label'] = data.get('event', '')

    try:
        # Render the graph to the specified file
        agraph.draw(output_path, prog='dot')
        print(f"Graph visualization saved to '{output_path}'")
    except Exception as e:
        print(f"Error generating graph visualization: {e}")
        print("Please ensure that graphviz is installed and in your system's PATH.")
