"""
Analyzes the state graph generated by the simulation engine to find issues.
"""
import networkx as nx
from src.core.models import SystemModel
from src.core.expressions import safe_eval

class Analyzer:
    def __init__(self, model: SystemModel, state_graph: nx.DiGraph):
        self.model = model
        self.graph = state_graph

    def find_violations(self, expression_list, violation_type):
        """Generic function to find states that violate a given list of expressions."""
        violations = []
        for node in self.graph.nodes:
            state_dict = dict(node)
            for item in expression_list:
                try:
                    # If the expression evaluates to False, it's a violation.
                    if not safe_eval(item.expression, state_dict):
                        violations.append({
                            violation_type: item.description,
                            "state": state_dict,
                            "path": self._find_path_to_node(node)
                        })
                except Exception:
                    # Could be NameError if a variable isn't in this state, etc.
                    continue
        return violations

    def find_constraint_violations(self):
        """Finds states that violate any of the model's constraints."""
        return self.find_violations(self.model.constraints, "constraint")

    def find_goal_violations(self):
        """Finds states that violate any of the model's goals."""
        return self.find_violations(self.model.goals, "goal")

    def find_deadlocks(self):
        """Finds states with no outgoing transitions."""
        deadlocks = []
        for node in self.graph.nodes:
            if self.graph.out_degree(node) == 0:
                deadlocks.append({
                    "state": dict(node),
                    "path": self._find_path_to_node(node)
                })
        return deadlocks

    def _find_path_to_node(self, target_node):
        """Helper to find the shortest path of events from the initial state to a target."""
        try:
            # Find the path of state tuples
            path_nodes = nx.shortest_path(self.graph, source=tuple(sorted([(var.name, var.initial_value) for var in self.model.states])), target=target_node)

            # Convert the path of nodes to a path of event names
            path_events = []
            for i in range(len(path_nodes) - 1):
                edge_data = self.graph.get_edge_data(path_nodes[i], path_nodes[i+1])
                # In a multigraph, there could be multiple edges; we take the first.
                event = edge_data.get('event', 'unknown_event')
                path_events.append(event)
            return path_events
        except (nx.NetworkXNoPath, nx.NodeNotFound):
            return ["path not found"]
